### ISSUE TITLE
Update gallery images

### ISSUE THREAD

**Issue by divyam3897** [pulug/sfd17#8]
Update them from images here: https://goo.gl/8jsjUc

**Comment by AkshayCHD** [comment]
Hello sir i want to work on this issue, could you just tell how many images do i have to use.

**Comment by divyam3897** [comment]
Keep the count same.

**Comment by AkshayCHD** [comment]
But they are too many, the file be of several GB

**Comment by divyam3897** [comment]
compress the images, if on Linux image magick is one tool but make sure that you don't disturb the quality.
